### ISSUE TITLE
OpenBIOS game compatibility list

### ISSUE THREAD

**Issue by davidhedlund** [grumpycoders/pcsx-redux#1029]
What do you think about the idea of writing a game compatibility list for OpenBIOS (starting with the absolutely most popular games: https://en.wikipedia.org/wiki/List_of_best-selling_video_games, https://en.wikipedia.org/wiki/List_of_video_games_considered_the_best)?

Related: Example of game compatibility emulator lists:

* Cemu: https://compat.cemu.info/
* Yuzu: https://yuzu-emu.org/game/
* Dolphin: https://dolphin-emu.org/compat/
* PCSX2: https://pcsx2.net/compat/

**Comment by davidhedlund** [comment]
https://github.com/grumpycoders/pcsx-redux/issues/1027

**Comment by wheremyfoodat** [comment]
There is a compatibility sheet already
https://docs.google.com/spreadsheets/d/1UNGs7uYb8viAbm7YJaf1CR4dkgX7ZzntUdcowGsjcVc/edit?usp=sharing

It is a tad outdated and incomplete though.

**Comment by davidhedlund** [comment]
> There is a compatibility sheet already https://docs.google.com/spreadsheets/d/1UNGs7uYb8viAbm7YJaf1CR4dkgX7ZzntUdcowGsjcVc/edit?usp=sharing
> 
> It is a tad outdated and incomplete though.

Thanks. But OpenBIOS users don't have access to it, it's not published in https://github.com/grumpycoders/pcsx-redux

**Comment by nicolasnoble** [comment]
So, as @wheremyfoodat said, the list is outdated and read-only. We're not the authors of it, and many bugs have been fixed in the meantime. I think the list is actually linked from somewhere in the README of OpenBIOS, but I may be wrong.

It might be beneficial to try and redo another pass on this, using the list as an initial data point, and this time, maybe make it an md table in the repository? Of course this is an immense amount of work, especially when it's about testing if the problem is an emulator bug, or an openbios bug, since it requires testing on the real hardware, and we don't necessarily have the time to work on this ourselves.

**Comment by davidhedlund** [comment]
> So, as @wheremyfoodat said, the list is outdated and read-only. We're not the authors of it, and many bugs have been fixed in the meantime. I think the list is actually linked from somewhere in the README of OpenBIOS, but I may be wrong.
> 
> It might be beneficial to try and redo another pass on this, using the list as an initial data point, and this time, maybe make it an md table in the repository?

Great! In src/mips/openbios/COMPATIBILITY.md?

**Comment by davidhedlund** [comment]
@nicolasnoble Can you please answer when you have time?

**Comment by nicolasnoble** [comment]
I mean, sure, if you want to submit a PR to add the file, go ahead. We can see about the exact contents during the PR, but I'm not too concerned.
