### ISSUE TITLE
Fullscreen render unticked: resizing main window affects rendering of output window

### ISSUE THREAD

**Issue by fuerchter** [grumpycoders/pcsx-redux#1065]
### Describe the bug

The game in the Output window renders in a very pixelated way. You seem to know other things related to the renderer that this affects (according to our discord messages).

### Expected behavior

Resizing the main window does not affect how a game is rendered in the Output window.

### Steps to reproduce the bug

1. Start PCSX-Redux
2. Untick Debug->Fullscreen render
3. Start any(?) game
4. Resize the height of the main window (just titled PCSX-Redux) to be very small

(I brought this up in the discord in #general earlier with [this](https://cdn.discordapp.com/attachments/567975889879695363/1045038525004927067/fullscreen_render.mp4) video attached)

### Operating System

Windows 11 64-bit

### PCSX-Redux version

Version: 11559.20221123.4.x64
Changeset: 1c2be2ab90bf30189d4efbf42ede7900b30a7176
Date & time: 2022-11-23 07:15:40

### CPU model

AMD Ryzen 5 3600 6-Core Processor 3.59 GHz

### GPU model

NVIDIA Geforce GTX 1660 SUPER

### BIOS version

OpenBIOS detected (fbe75b59)

### CPU emulation mode

Interpreter

### GPU emulation mode

Software

**Comment by wheremyfoodat** [comment]
Any example image?

On first thought this might be caused by the texture filtering mode you've picked. To configure it, go to configuration->GPU and tick/untick the "Use Linear Filtering" option

Linear filtering will sometimes make the image blurry. Not using linear filtering and scaling the image by a weird factor (eg 1.7x) will sometimes make the image look pixelated and sharp.

In the future I'll try to add an integer scaling option. This will let you scale the image only by an integer factor (eg 1x, 2x, 4x) but without any artifacting.

**Comment by wheremyfoodat** [comment]
Oh oops

**Comment by nicolasnoble** [comment]
This code here needs to account for non full screen render :

https://github.com/grumpycoders/pcsx-redux/blob/main/src/gui/gui.cc#L679

**Comment by fuerchter** [comment]
Minimizing instead of resizing the main window has a similar effect on this by the way (I'm assuming both have the same root). Bringing this up for completeness.
