### ISSUE TITLE
All the Options of Memory Editor #1 are not saved to and loaded from a file or disk on close, open or reboot of PCSX-Redux

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1092]
Currently Memory Editor #1 has six Options in PCSX-Redux and they are:

1. cols (16 by default)
2. Show Data Preview (Checked by default)
3. Show HexII (Unchecked by default)
4. Show Ascii (Checked by default)
5. Grey out zeroes (Checked by default)
6. Uppercase Hex (Unchecked by default)

I **personally prefer** both "Grey out zeroes" **un**checked and "Uppercase Hex" **checked** but when I have to reboot PCSX-Redux no matter what is the reason they return back to their defaults after the reboot! Even "cols" return back to 16 after the reboot!

It seems that PCSX-Redux doesn't save all the Options of Memory Editor #1 to disk or a file on close or reboot to remember my preferences and hence doesn't load them from disk or a file either on open or after reboot.

Every software that respects itself always save all user settings and preferences to disk or a file on close and load all user settings and preferences from disk or a file on open.

Please fix this issue because this is **slightly** annoying me.

**Comment by wheremyfoodat** [comment]
Which options would you like to see being saved? We haven't really made the mem editor widgets save anything because changing settings is quite a fast and painless process and most people are pretty happy with the defaults. Additionally, we use a stock version of the ImGui Club widget so modifying it is a tad of a pain in the ass without making a wrapper around it. That will probably become necessary for implementing certain features in the future though.

**Comment by buruto** [comment]
> Which options would you like to see being saved? We haven't really made the mem editor widgets save anything because changing settings is quite a fast and painless process and most people are pretty happy with the defaults. Additionally, we use a stock version of the ImGui Club widget so modifying it is a tad of a pain in the ass without making a wrapper around it. That will probably become necessary for implementing certain features in the future though.

Sorry that I was late, something distracted me and drew my attention.
