### ISSUE TITLE
Konami System 573 tutorial?

### ISSUE THREAD

**Issue by soundsnow** [grumpycoders/pcsx-redux#1704]
Hi @spicyjpeg How to run Konami System 573 games? I installed Winlator and the latest PCSX Redux GUI version but it didn't work. There is only one 3D block

File - Open Disk Image - Salaryman Champ - Tatakau Salaryman (Japan).cue
File - Load Binary - Salaryman Champ - Tatakau Salaryman (Japan).bin
Emulation - Start Emulation

Does it support or will support System 573? I mean whether it can run, not whether it can be played. Someone wants to add this emulator to a wiki page, but he's not sure
By the way, I would like to ask if this emulator supports or will support other Namco, Konami and Sony arcade systems. Because I saw your Open BIOS 573 PR

**Comment by nicolasnoble** [comment]
PCSX-Redux is a far cry from being able to run System 573 roms, for various reasons. It most likely never will support it, and this will never be a focus of the work being done here.

**Comment by spicyjpeg** [comment]
> By the way, I would like to ask if this emulator supports or will support other Namco, Konami and Sony arcade systems. Because I saw your Open BIOS 573 PR

The OpenBIOS System 573 build is really just a minimal modification that prevents it from crashing on real hardware, but does *not* otherwise add support for accessing the 573's ATAPI CD-ROM drive or flash memory (not without [embedding an external program](https://github.com/spicyjpeg/573in1#download-and-usage) into it at least). Also, keep in mind that OpenBIOS is completely independent from the rest of the emulator and its features may not necessarily reflect the ones implemented by pcsx-redux itself.
