### ISSUE TITLE
Frame limiter issue

### ISSUE THREAD

**Issue by liuk7071** [grumpycoders/pcsx-redux#390]
When disabled I get very high frame rates, but if I enable it it doesn't run at full speed.

**Comment by nicolasnoble** [comment]
Yeah I need to heavily rewrite this.

**Comment by lorn10** [comment]
Little status update regarding this topic. It looks that there was some progress in this matter. Out of mine view the latest PCSX-redux builds from end of May are running normally (at normal speed) with frame limiter enabled. (I should note that I am on Linux/Wine not native Windows.)

There may in this topic also some differences between the 32bit and 64bit build and which recompiler is used. In my case under Wine, the 64bit build always starts up with the standard interpreter while the 32bit build uses the optimized DynaRec variant. However, the frame limiter works in both as it should, and in my case the difference between the two is not gigantic. The DynaRec recompiler runs in the PSX Bios system menu with a maximum of around 1000 fps while the interpreted recompiler reaches around 800 fps. This seems to be a quite good value for a interpreted recompiler I think.

@nicolasnoble Wouldn't it make sense to set the standard value for the "Frame limiter" to enabled instead of disabled? (In my case I can activate it but after a restart of the emulator it is again off. Other value-changes are correctly stored and present after a restart.)

**Comment by wheremyfoodat** [comment]
Regarding the interpreter/dynarec stuff:
Redux's only dynarec target currently is x86-32. Hence 64-bit builds being locked to the interpreter.
The interpreter is decently fast as long as the emulator's debug mode is turned off, yeah.
Obviously a properly optimizing JIT targetting actually modern architectures (Mostly x86-64 and AA64 are still used in PCs and mobile devices, with the occasional ARMv7 device) could potentially be way faster but would require dumping a large part of the code base and rewriting it from scratch.

A lot of optimizations are currently kind of impossible, like proper register allocation, due to either x86-32's nature itself being an obstacle (in this case, it has 8 GPRs, with eax, edx and esp being partially special purpose), some are hard/not worthwhile to implement in a single-pass JIT that's kind of tainted by technical debt. Some notable missing stuff is proper tail call elimination and block linking, or hardware-accelerated fastmem. Latter also has the problem of requiring lots of platform-specific code and being quite a tad more complex than the current solution.

**Comment by nicolasnoble** [comment]
Proper FPS limit is in #587.
