### ISSUE TITLE
Feature request: Build PCSX-Redux Windows binaries more Wine compatible

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#474]
Hi there

Here follows a somewhat special "feature request". ;-) Would it be possible to build future PCSX-Redux Windows binaries more Wine compliant? I think in this regard especially at the Cxbx-Reloaded (Xbox) emulator. That one runs awesome great also under Wine (on Linux).

I know PCSX-Redux supports in contrast to Cxbx-R natively Linux, - so the first choice is to build own PCSX-Redux Linux binaries. However, this is not so trivial, especially for Linux-Noobs. ;-)

Furthermore a Wine compliant Windows build may be theoretically also useful for debugging & identify problems related to OpenGL. As everybody knows, the OpenGL support in Linux is thanks to the Mesa drivers absolute top class. The Windows OpenGL driver state is unfortunately behind and incomplete, - this is true especially for AMD and a little less also Intel.

At the moment PCSX-Redux is crashing because of some unimplemented Windows.Gaming.Input functions (possibly DirectInput related) in Wine. Cxbx-R works most likely because it seems more focused on XInput. (All other DInput related stuff is handled over a SDL2 library.) Whatever, more information can be found here:

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1713
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/156

[backtrace_pcsx-redux3828.txt](https://github.com/grumpycoders/pcsx-redux/files/6366751/backtrace_pcsx-redux3828.txt)
[backtrace_pcsx-redux3828console.txt](https://github.com/grumpycoders/pcsx-redux/files/6366754/backtrace_pcsx-redux3828console.txt)

**Comment by nicolasnoble** [comment]
Well, so, with regards to input, the current code straddles between SDL2 and GLFW3. I'm going to remove SDL2 "soon" to only rely on GLFW3 for all things input-related. The current situation may be what's causing the troubles when running the Windows binary through Wine.

Of course, as you mentioned, this could also be the first layer of issues, with more behind it after it'd be fixed, which potentially may be a big yak shave.

But all in all, as you also mentioned, there is a native Linux build supported, with an extremely simple build paradigm of running `make` or `./dockermake.sh`. The build requires only very few and easy to acquire dependencies, and is being continuously tested. There are also a couple of Linux packages available in the wild, and so I believe the path of least resistance here is to continue supporting the current Linux build as is. 

If after the GLFW3 migration, the Wine binary works, or fails on something else that's fixable, why not, but otherwise, I'm not going to go out of my way to make it work while the Linux build works, and works in fact better than the Windows one.

**Comment by lorn10** [comment]
Thanks Nicolas Noble for this informative and super detailed answer.

Will look into building own PCSX-Redux Linux binaries, - most likely I will learn again a lot. But I will also test from time to time the Wine behavior of the Windows builds. ;-)

**Comment by ergo720** [comment]
> Cxbx-R works most likely because it seems more focused on XInput. (All other DInput related stuff is handled over a SDL2 library.) 

Small correction: CxbxR uses DInput directly to control the keyboard and mouse devices, it just doesn't use it to handle the controllers (which are handled by either XInput or SDL2 instead).

**Comment by lorn10** [comment]
Here follows a little status update, - newer PCSX-Redux builds are now starting up **GREAT** in **Wine 6.8**! I can confirm this for the current **nightly 3879** which works totally error-free, - awesome. So it seems that the removing of the "SDL stuff" and the migration to "GLFW3" has effectively fixed the mentioned issues.

However, I am for whatever reason unable to load my original "Crash Bandicoot PlayStation CD" in PCSX-Redux. It looks that it is (currently) only possible to load ISO files and PlayStation binaries. Whatever, maybe there exist also an issue at the Wine side...

Many thanks to @nicolasnoble for the whole work in this matter!

![pcsx-redux-3879](https://user-images.githubusercontent.com/9931771/118006016-318a5300-b34b-11eb-8644-7029bcbff893.png)

![pcsx-redux-3879mainmenu](https://user-images.githubusercontent.com/9931771/118006048-37803400-b34b-11eb-84ad-3a7bd78643db.png)

**Comment by nicolasnoble** [comment]
There is no physical cdrom support in pcsx-redux. Only ISO files. I might add cdrdao file format support however, in order to let people create images using this fantastic tool.

**Comment by lorn10** [comment]
Thanks for the fast reply, - so this is not a bug in Wine or PCSX-Redux. At the moment, real CD support is simply not implemented.... Whatever, I am waiting very excited onto the future PCSX-Redux developments. :+1: Many thanks again for the great work! 

PS I think that PCSX-Redux will get good PS1 emulation before the PCSX2 devs will implement it finally reliable. ;-)
