### ISSUE TITLE
VRAM viewer crashes the emulator

### ISSUE THREAD

**Issue by glitch-in-the-herring** [grumpycoders/pcsx-redux#570]
I am using version 4908.20210815.2.x64. Whenever I click "Debug" -> "VRAM Viewers" -> "Show Main VRAM Viewer" or any of the other options below it, it would crash the emulator. The last version where this doesn't crash is version 4818.20210811.1.x64.

I am running Windows 10, GTX 1650 Ti. I have not changed any of the settings in the emulator, loaded any game, or started emulation. It crashes whether or not emulation has started or any game has been loaded

**Comment by wheremyfoodat** [comment]
@glitch-in-the-herring
Your crash seems to stem from the recent shader editor changes. Can you try running Redux from cmd/powershell and tell us if you happen to see any errors in the console after crashing? Also delete any .lua/.glslv/.glslp files that might be in your Redux folder.

**Comment by glitch-in-the-herring** [comment]
@wheremyfoodat The console does not output anything, it stops printing anything after the window launches. I do not have any .lua/.glslv/.glslp files in the folder.

**Comment by wheremyfoodat** [comment]
@glitch-in-the-herring Do you happen to have the ability to build Redux, or should I send you a test build to try on your machine?

**Comment by glitch-in-the-herring** [comment]
@wheremyfoodat I don't have the ability to build Redux right now, I would appreciate that.

**Comment by wheremyfoodat** [comment]
@glitch-in-the-herring Alright, I'll be back asap

**Comment by glitch-in-the-herring** [comment]
@wheremyfoodat This works, it also works while running a game.

**Comment by wheremyfoodat** [comment]
@glitch-in-the-herring
Alright, that's very good. I can't thank you enough for reporting this issue and testing the exe in the Google Drive link.

That exe is a build artifact from #569 that comments out a line in the default fragment shader for VRAM viewers (You can find this in src/gui/widgets/vram-viewer.cc).

It seems like your GPU doesn't enjoy that shader. To confirm this you can open a VRAM viewer, choose "View" and then "Show Shader Editor" 

Look for the text `//layout(origin_upper_left) ...` in the second of the three windows, and try removing the `//`.

If my suspicion is true, removing that should make it crash again. This is probably caused by GPU driver problems, but since this problem has come up in the past before, it'd probably be better to revert that change.

**Comment by glitch-in-the-herring** [comment]
@wheremyfoodat Yep, it returns an error
![image](https://user-images.githubusercontent.com/70984234/129565869-d8bb0c20-d853-404f-83a9-d5210236e604.png)

**Comment by wheremyfoodat** [comment]
@glitch-in-the-herring Alright, thanks for your cooperation and for helping us investigate it, we'll fix it as soon as possible.
