### ISSUE TITLE
Latest build doesnt open in my windows

### ISSUE THREAD

**Issue by Felipefpl** [grumpycoders/pcsx-redux#792]
### Describe the bug

I click twice to open redux on win7 x64 but it doesnt work, the open quickly opens and close itself.

### Expected behavior

The window should open.

### Steps to reproduce the bug

Click 2x in the exe to open the emu.
Nothing happens.

### Operating System

Windows 7 x64

### CPU model

Intel sandy-bridge

### GPU model

intel hd 2000

### BIOS version

scph1001

### CPU emulation mode

Recompiler

### Additional information

nothing to add.

**Comment by nicolasnoble** [comment]
There's a very good chance that Windows 7 is simply not going to be supported anymore. Microsoft fully deprecated it, and removed all CI capabilities for it recently. It's become impossible to make any significant effort to work on it and debug.

Still, try the following:

- delete pcsx-redux.exe
- rename pcsx-redux.main to pcsx-redux.exe
- open a cmd.exe window and navigate to where you have downloaded pcsx-redux
- run `pcsx-redux -stdout`

And let us know if it reports some more information on what's going on.

**Comment by Felipefpl** [comment]
Hi, thanks for the help, i did what you suggested but it didnt work. :/

**Comment by nicolasnoble** [comment]
Also try `-safe`.

**Comment by Felipefpl** [comment]
Tried -safe, same result unfortunately.

**Comment by nicolasnoble** [comment]
Not really sure what's going on. We've found a few people who still have Windows 7 machines and it's working properly. The fact it closes without any message is frustrating and problematic. You've been downloading a fresh build extracted in its own folder, right? Did it use to work before? Is there any way you can try and pinpoint at which release it stopped working for you?

**Comment by Felipefpl** [comment]
I extracted pcsx to its own folder, i never used redux before now.

I have a suggestion, it's bugtrap https://github.com/bchavez/BugTrap - it creates detailed changelogs of crashes and can be used with any program, not only .net unlike it says on its page, If it was embedded on redux i could try to open it and see if it creates a crash's log of what happened.

**Comment by wheremyfoodat** [comment]
You could also probably compile Redux locally and run it in a debugger, like Visual Studio's, which will most likely give you much more helpful results.

**Comment by Felipefpl** [comment]
I'm not a coder neither i know how to use a compiler, also, this isnt a good solution to suggest to every person who may come here with problems to run redux. ;)

**Comment by lorn10** [comment]
@Felipefpl 

Sorry tho say this but you really should migrate to a new PC or simply switch to **Linux**. Your Windows **Intel GPU drivers** are effectively only compatible to **OpenGL 3.1** and are most likely of a "not so good quality". So this bug here is finally a double of #272.

I switched almost all my computers to Kubuntu 20.04 LTS which runs really awesome also at older hardware. And of course, PCSX-Redux runs great thanks to the **Mesa drivers** which offer full **OpenGL 3.3** support also on Intel Sandy Bridge based GPUs like my Intel HD 2000. :+1: 

Whatever, it looks that this topic and #272 can be closed.

And @wheremyfoodat, maybe it would make sense to think about an OpenGL **ES** 2.0 renderer? A such one would be quite useful at mobile phones and tablets. OpenGL ES 2.0 is furthermore supported at all Windows 10/11 systems through [Angle](https://github.com/google/angle) and it is as well available on all never Mac OS versions through the `GL_ARB_ES2_compatibility` extension.

**Comment by wheremyfoodat** [comment]
@lorn10 I haven't thought much about OpenGL ES, giving that Redux currently mostly targets PCs and desktop OpenGL works fine there.

If by "renderer" you mean to emulate the PS1 GPU, then it'd be probably best to make a renderer for desktop GL and see how much stuff needs to be changed to work with ES. ES is definitely no slouch and it's decently interchangeable with desktop GL, but it's missing some stuff missing from desktop OpenGL that our code might be using. For example, it does away with most legacy stuff (some of which no one should be using in 2022 anyways, like glBegin and friends for drawing stuff)  and does away with some other niche stuff or locks it behind non-core extensions (For example, I don't remember if a standard 🇪🇸implementation needs to have support for RGB555 textures, which Redux uses).

If by "renderer", you mean for the whole app (Drawing the GUI and stuff), ImGui already supports ES which is very nice, but some code would probably need to be revisited still. It's nice that ES is decently easy to shoehorn in place of desktop GL code though.

If we were to target OpenGL ES though, it would probably be ES 3.0, 3.1 or 3.2. ES 2 is not horrible, but it is very old and was made to be up to par with pretty much ancient OpenGL. ES 3.x is still very widely supported in the smartphone/tiny computer market, and is probably what's closest to the version of OpenGL version that Redux requires. Ironically, ES 3.1/3.2 support some nice things that current Redux can't even use without driving the OpenGL requirement way up. Particularly, compute/geometry/tesselation shaders.

**Comment by lorn10** [comment]
Thanks for this super informative answer. :+1: 

Well, maybe I didn't understand all the semantics in every detail but it looks that the OpenGL ES 2.0+ API is somehow more "uniform" and "supplementary" than the classical OpenGL API? For example, at Wikipedia it is written "[OpenGL ES 3.0 is backwards compatible with OpenGL ES 2.0, enabling applications to incrementally add new visual features to applications.](https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_3.0)".

Yes, this doesn't mean that you can use higher OpenGL ES 3.x functions on lower hardware but most likely you don't have to worry so much about compatibility or context profiles. I understand it like that every ES 2.0 application can run (theoretically) without any modification 1:1 on higher ES level hardware.

So maybe it would be possible to make a uniform "OpenGL ES renderer" which operates at minimum with ES 2.0 and uses for more effects ES 3.x features if available.

Whatever, this is here now really off-topic. :wink: 

PS The available texture format depends also on the driver provider. For example, the [Mesa OpenGL ES 2.0](https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_2.0) implantation brings a lot of optional extensions which are not part in the core specification.

**Comment by wheremyfoodat** [comment]
@lorn10 

> Well, maybe I didn't understand all the semantics in every detail but it looks that the OpenGL ES 2.0+ API is somehow more "uniform" and "supplementary" than the classical OpenGL API? For example, at Wikipedia it is written "[OpenGL ES 3.0 is backwards compatible with OpenGL ES 2.0, enabling applications to incrementally add new visual features to applications.](https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_3.0)".

This is generally true for the desktop OpenGL API and GL flavours like ES, yeah. They very rarely remove features from previous versions (They "removed" a bunch of legacy stuff on OpenGL 3.1, but you can still use it on a compatibility profile, so it's kinda still there). However, when OpenGL ES was spun off from desktop OpenGL, they removed a decent bit of the older APIs, most notably most of the fixed-function pipeline (Early ES is still fixed function - it didn't support shaders until 2.0 - though it removed support for stuff like glBegin/glEnd and replaces them with modern vertex arrays). In addition, some of the nicher desktop GL stuff was removed, because it wasn't being used very often, so there was no reason for the spec to require it.

Keep in mind that more features -> more stuff needs to be implemented in hardware, for the most part.  Mobile/embedded GPUs were meant to be *very* small (A mobile GPU is typically a tiny chip, on a tiny SoC), run very cool and on little power. This is why they made it so even though ES versions are compatible with past ES versions, they're not compatible with past desktop GL versions.

> Yes, this doesn't mean that you can use higher OpenGL ES 3.x functions on lower hardware but most likely you don't have to worry so much about compatibility or context profiles.
Yeah, ES doesn't have compatibility/core profiles, but we'd still need to apply a minimum version for a context. The emulator really needs *some* newer features at the very minimum.

> So maybe it would be possible to make a uniform "OpenGL ES renderer" which operates at minimum with ES 2.0 and uses for more effects ES 3.x features if available.
The problem with this is feature parity - it's very important that all people using Redux have access to more or less the same features. [The only feature rn that only works on some GPUs is OpenGL error reporting](https://github.com/grumpycoders/pcsx-redux/blob/7b17258ff6406124e627794f38745f91a522f9b6/src/gui/gui.cc#L424), a feature disabled by default that I'm sure 99% of people don't know is there. If stuff like graphical effects in games only appeared on some GPUs that would cause a couple problems.

- Debugging is **hell**
- The experience you get would depend heavily on your GPU and drivers.
So what's ideal is to mostly use core features (Every GPU supporting a specific OpenGL (ES) spec needs to support them) and enforce a minimum spec version that will cover everything we need.

> PS The available texture format depends also on the driver provider. For example, the [Mesa OpenGL ES 2.0](https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_2.0) implementation brings a lot of optional extensions which are not part in the core specification.
As mentioned before, whether optional extensions exist depend on your GPU and drivers, so taking advantage of them will cause the above problems unless they're more-or-less universal. In addition, some driver developers barely manage to support the core GL spec (And by "barely manage", I mean it's "supported" except it's often buggy. This isn't super uncommon - one of the main reasons new drivers are constantly released is that GPU drivers are extremely complex, so bugs come and go). So I don't really count on them to support optional extensions, much less support them properly.

**Comment by nicolasnoble** [comment]
Ugh, I didn't notice that the report had yet another Intel HD something that may indeed just not start. That being said, this is supposed to be handled. There's supposed to be an error message going on the screen that says the OpenGL context couldn't have been created, like so:

![Screenshot from 2022-04-01 16-32-04](https://user-images.githubusercontent.com/7281574/161354247-c0e412ea-d424-48e1-a5a3-2310bada4381.png)

So I'm not totally sure what's going on still, so I'm not fully convinced this is the issue (the above was taken on Windows 7 using Qemu without installing the hardware accelerated drivers).

With regards to how we're rendering things, (both the UI, and the actual emulated output), the constrains on OpenGL as we're doing it right now is mainly about the convenience for us, as code authors. We don't necessarily have the means to automatically test and develop on a wide range of devices and GPUs, and the restriction is still very lax anyway.

This package however might help:

https://github.com/pal1000/mesa-dist-win/releases

It can provide generic OpenGL drivers for older hardware. It's worth trying. Running the installer should display:

```
-------------------------------------
Mesa3D system-wide deployment utility
-------------------------------------
Please make a deployment choice:
1. Core desktop OpenGL drivers
2. Core desktop OpenGL drivers + Intel swr
3. Install DirectX IL for redistribution only
4. Microsoft OpenGL over D3D12 driver only (replaces Mesa core desktop OpenGL drivers)
5. Mesa3D off-screen render driver gallium version (osmesa gallium)
7. Mesa3D graw test framework
8. Update system-wide deployment
9. Remove system-wide deployments (uninstall)
10. Exit
Enter choice:
```

Just select option 1, "Core desktop OpenGL drivers".

**Comment by lorn10** [comment]
Really really cool, Mesa drivers for Windows! :+1: I've heard about this before, but I effectively didn't believe their exist in a "practical way". It seems that has changed, - at least for **Intel iGPU** hardware...

@wheremyfoodat The mentioned additional "optional" Mesa OpenGL ES 2.0 extensions are effectively widely used ones and most of them became "core" in ES 3.0. :wink:

**Comment by wheremyfoodat** [comment]
@lorn10 Yeah that's part of the reason I prefer ES 3.x over ES 2. Though for now our first priority would be to make our own PS1 GPU core using regular desktop OpenGL, then see what should happen with platforms that only support 🇪🇸

**Comment by Felipefpl** [comment]
@nicolasnoble - Thank you for the help, i installed the mesa drivers as you suggested, it didnt work, like before i didnt even get that error message about opengl. Surely strange, but Aida64 reports i have 100% support for OpenGl 3.1 and 70% support for OpenGl 3.3, i can even run Neverwinter Nights Enhanced Edition that is made for OpenGl 3.3 without any problem here. Is OpenGl 3.3 really that necessary? I mean, OpenGl 2.0 wouldnt work fine?

**Comment by wheremyfoodat** [comment]
@Felipefpl OpenGL 2.0 doesn't even support VAOs or framebuffers, and barely supports the basic shader types. There's no way Redux will work for it, probably ever. It's a spec that's almost older than me that was made when people were still struggling to move to programmable GPUs...

**Comment by Felipefpl** [comment]
@wheremyfoodat - Strange, that doesnt explain why epsxe uses a system that supports opengl 1 and 2 and afaik, lots of games work with it.

**Comment by nicolasnoble** [comment]
Alright, I'll be closing this one now.

**Comment by lorn10** [comment]
@Felipefpl 
**PCSX-Reloaded** is still OpenGL 2.1 based and should work for you. :wink: 

As mentioned it is also possible to install a Linux distro onto a 32 GB or better 64 GB USB flash drive. Maybe you give **[MX Linux](https://mxlinux.org/)** a try. I would recommend the variant with KDE desktop because it is quite similar to Windows 7 / 10. 

And if you have an EFI based system (like my 2006 iMac is) then you can install this distro even without any additional boot-loader. So you will effectively not change anything at your computer / laptop. :+1:

**Comment by Felipefpl** [comment]
lorn10 - Thanks for the hint, i tried reloaded but it's outdated for some time, i came to redux hoping it was going to work for me and who knows, emulate legend of dragoon better than all other emus i tried. A pity this wasnt teh case, but thanks anyways for all the help everyone gave me.

**Comment by lorn10** [comment]
For the record, - I have tested PCSX-Redux **build 8340** at my last Windows 7 based computer and it starts up perfectly well. :+1:

However, it should be mentioned that the corresponding Nvidia drivers are at **OpenGL 3.2** level. So in the end this seems to be a problem of the Intel iGPU OpenGL drivers and not Windows 7. Therefore it must be said to all Intel iGPU owners with that driver problem: **switch to Linux!** :stuck_out_tongue: 
![PCSX-Redux_build8340_win7](https://user-images.githubusercontent.com/9931771/161592364-bb6d5b7e-eebf-41d6-adb6-4545a7ee70a7.png)
