### ISSUE TITLE
Disney's Tarzan v 1.1 freeze

### ISSUE THREAD

**Issue by StanleyKid-22** [grumpycoders/pcsx-redux#850]
Hi-hello. There's a problem with Disney's Tarzan v 1.1.
PCSX-Redux in the 32-bit release freezes on the game main screen or before main screen appearing. 64-bit works fine.

**Comment by wheremyfoodat** [comment]
Hello.
I have not tested that game myself yet, but you're probably coming across a problem in the (deprecated) x86-32 dynarec that I don't really support anymore.

If you need to use a 32-bit build, you might want to turn the "dynarec CPU" option off for this game and reboot the emulator. Otherwise we recommend using 64-bit builds.

**Comment by StanleyKid-22** [comment]
OK, thanks so much. I'll try that.

**Comment by wheremyfoodat** [comment]
Np
